-- SQL UPDATES FOR CUSTOMER MODULE IMPROVEMENTS
-- Run this in your Supabase SQL Editor

-- 1. Update 'bookings' table for separate time structures (Point 3)
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS check_in_time TIME;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS check_out_time TIME;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_time TIME;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS rescheduled BOOLEAN DEFAULT FALSE;

-- 2. Update 'customer_notifications' for type classification (Point 7)
ALTER TABLE customer_notifications ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'INSUFFICIENT_PAYMENT';

-- 3. Create 'booking_reschedule_logs' table (Point 5)
CREATE TABLE IF NOT EXISTS booking_reschedule_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
    old_date DATE,
    new_date DATE,
    old_time TEXT,
    new_time TEXT,
    rescheduled_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Auto-delete customer order history after 3 days (Point 2)
-- Create a function to handle the cleanup
CREATE OR REPLACE FUNCTION delete_old_customer_data()
RETURNS void AS $$
BEGIN
    -- Delete orders older than 72 hours
    DELETE FROM orders WHERE timestamp < NOW() - INTERVAL '3 days';
    
    -- Delete completed/rejected/cancelled transactions older than 3 days
    DELETE FROM pending_orders 
    WHERE created_at < NOW() - INTERVAL '3 days' 
    AND status IN ('completed', 'rejected', 'cancelled');
    
    -- Delete completed/rejected/cancelled bookings older than 3 days
    DELETE FROM bookings 
    WHERE created_at < NOW() - INTERVAL '3 days' 
    AND status IN ('completed', 'rejected', 'cancelled');

    -- Cleanup notifications for completed orders (Point 7)
    DELETE FROM customer_notifications
    WHERE type = 'INSUFFICIENT_PAYMENT'
    AND order_id IN (
        SELECT CAST(id AS TEXT) FROM pending_orders WHERE status = 'completed'
    );
END;
$$ LANGUAGE plpgsql;

-- 4. Schedule the cleanup (Requires pg_cron extension enabled in Supabase)
-- SELECT cron.schedule('0 0 * * *', 'SELECT delete_old_customer_data()');

-- 5. Example query for Pre-order Total Summary (Point 6)
-- To be used in views or reports:
-- SELECT 
--   COALESCE(SUM(total), 0) as total_preorder_sales
-- FROM bookings 
-- WHERE type = 'preorder' 
-- AND status NOT IN ('rejected', 'cancelled');
